function csv = edgeUsageToCSV(edgeUsage,network)
    total = sum(cell2mat(values(edgeUsage)));
    csv = "A,B,Total,Percentage,Weight" + newline;
    for keyCell = keys(edgeUsage)
        k = keyCell{1};
        [node1,node2] = network.getNodePair(k);
        csv = csv ...
            + node1 + "," ...
            + node2 + "," ...
            + edgeUsage(k) + "," ...
            + (edgeUsage(k) / total)+ "," ...
            + network.Topology.AdjacencyMatrix(node1,node2) ...
            + newline;
    end
end

